services:
  db:
    image: postgres:16-alpine
    container_name: hospital_db
    environment:
      POSTGRES_DB: hospital
      POSTGRES_USER: hospital
      POSTGRES_PASSWORD: hospital
    ports:
      - "5432:5432"
    volumes:
      - hospital_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hospital -d hospital"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: .
    container_name: hospital_app
    ports:
      - "9060:9060"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hospital
      SPRING_DATASOURCE_USERNAME: hospital
      SPRING_DATASOURCE_PASSWORD: hospital
      JWT_SECRET: "change-me-in-real-env"
    depends_on:
      db:
        condition: service_healthy

volumes:
  hospital_db_data:
