server:
  port: 9060

spring:
  datasource:
    url: jdbc:postgresql://db:5432/hospital
    username: hospital
    password: hospital
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secret: ${APP_JWT_SECRET:CHANGE_ME_TO_A_LONG_RANDOM_SECRET_CHANGE_ME_1234567890_1234567890}
    expirationMinutes: ${APP_JWT_EXP_MINUTES:120}

seed:
  admin:
    username: ${SEED_ADMIN_USERNAME:admin}
    email: ${SEED_ADMIN_EMAIL:admin@hospital.local}
    password: ${SEED_ADMIN_PASSWORD:Admin123!}
